# A Hugo Site Example Using Oriclone Theme

baseURL      = "https://vigorous-swirles-2642fd.netlify.com/"
languageCode = "en-us"
title        = "Yet Another Open Source Blog"
theme        = "oriclone"

Paginate     = 7

PygmentsCodeFences = true
PygmentsStyle      = "monokai"

# https://github.com/gohugoio/hugo/issues/4288
# uglyurls = true

[params]
  description = """\
    Learn and Discover Open Source with Daily Genuine Experience.
    From Coding, Front End, Back End, Database, and Static Site Generator.
    """

  opengraphimage = "assets/site/images/logo-gear-opengraph.png"

[permalinks]
  backend    = ":section/:year/:month/:day/:slug"  
  code       = ":section/:year/:month/:day/:slug"
  frontend   = ":section/:year/:month/:day/:slug"
  ssg        = ":section/:year/:month/:day/:slug"

[taxonomies]
  category = "categories"
  tag = "tags"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[mediaTypes]
  [mediaTypes."text/yaml"]
    suffixes = "yml"

[outputFormats]
  [outputFormats.yml]
    baseName    = "index"
    mediaType   = "text/yaml"
    isPlainText = true
  [outputFormats.txt]
    baseName    = "index"
    mediaType   = "text/plain"
    isPlainText = true
