# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Oriclone"
license = "MIT"
licenselink = "https://gitlab.com/epsi-rns/epsi-rns.gitlab.io/blob/master/themes/oriclone/LICENSE.md"
description = "A Base theme for building full featured Hugo sites"
homepage = "https://epsi-rns.gitlab.io"
tags = ["website", "boostrap", "responsive"]
features = ["posts", "archives"]
min_version = 0.3

[author]
  name = "epsi"
  homepage = "https://gitlab.com/epsi-rns"
